from ._anvil_designer import ScenariosTemplate
from anvil import *
import anvil.users
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables


class Scenarios(ScenariosTemplate):
  def __init__(self, **properties):
    # Set Form properties and Data Bindings.
    self.init_components(**properties)

    # Any code you write here will run before the form opens.

  def button_1_click(self, **event_args):
    scenario_list = {
    "S0":"Howling in the Snow",
    "S1":"A Town in Flames",
    "S2":"Algox Scouting",
    "S3":"Algox Offensive",
    "S4":"Heart of Ice",
    "S5":"Frozen Crypt",
    "S6":"Avalanche",
    "S7":"Edge of the World",
    "S8":"Crystal Trench",
    "S9":"Glowing Catacombs",
    "S10":"Crystal Enclosure",
    "S11":"Snowscorn Peak",
    "S12":"Temple Entrance",
    "S13":"Frozen Fjord",
    "S14":"Jagged Shoals",
    "S15":"Ancient Spire",
    "S16":"Derelict Elevator",
    "S17":"Haunted Vault",
    "S18":"Crystal Fields",
    "S19":"Skyhall",
    "S20":"Temple of Liberation",
    "S21":"Realm of Endless Frost",
    "S22":"Ice Floes",
    "S23":"Spire Basement",
    "S24":"Upper Spire",
    "S25":"Rusted Tunnels",
    "S26":"Quatryl Library",
    "S27":"Depths of Delirium",
    "S28":"Summit Meeting",
    "S29":"War of the Spire A",
    "S30":"War of the Spire B",
    "S31":"Crackling Tunnel",
    "S32":"Raven's Roost",
    "S33":"Thawed Wood",
    "S34":"Top of the Spire",
    "S35":"Scrap Pit",
    "S36":"Buried Ducts",
    "S37":"The Dead Mile",
    "S38":"The Way Forward",
    "S39":"Corrupted Camp",
    "S40":"Relief Effort",
    "S41":"Unfettered Shard",
    "S42":"Sunless Trench",
    "S43":"Overrun Barricade",
    "S44":"Nerve Center",
    "S45":"Living Glacier",
    "S46":"Dead Pass",
    "S47":"Carrion Ridge",
    "S48":"Blizzard Island",
    "S49":"Beneath Sea and Stone",
    "S50":"Explosive Descent",
    "S51":"Orphan's Halls",
    "S52":"Fleeting Permanence",
    "S53":"Underwater Throne",
    "S54":"Among the Wreckage",
    "S55":"Change of Heart",
    "S56":"Call of the Harbinger",
    "S57":"Sanctuary of Snow",
    "S58":"Orphan's Core",
    "S59":"Automaton Uprising",
    "S60":"Uniting the Crown",
    "S61":"Life and Death",
    "S62":"The Unfettered Seal",
    "S63":"The Savvas Seal",
    "S64":"The Frosthaven Seal",
    "S65":"A Strong Foundation",
    "S66":"Elemental Cores",
    "S67":"Core Attunement",
    "S68":"The Face of Torment",
    "S69":"Sacred Soil",
    "S70":"The True Oak",
    "S71":"Invasion of the Dock",
    "S72":"A Giant Block of Ice",
    "S73":"Flotsam",
    "S74":"Gaps in the Road",
    "S75":"Infiltrating the Lair",
    "S76":"Apotheosis",
    "S77":"Fish King's Ascension",
    "S78":"The Lurker Problem",
    "S79":"Relic",
    "S80":"Relic Renewed",
    "S81":"Ruinous Research Lab",
    "S82":"Expedition North",
    "S83":"Rising Brine",
    "S84":"Here There Be Oozes",
    "S85":"Deadly Pastimes",
    "S86":"The Lady in White",
    "S87":"The Collection",
    "S88":"Collection's Capstone",
    "S89":"A Contained Fire",
    "S90":"Frozen Treasure",
    "S91":"Shoreline Scramble",
    "S92":"Sinking Ship",
    "S93":"Midwinter Brawl",
    "S94":"A Grand View",
    "S95":"To Bury the Dead",
    "S96":"Underground Station",
    "S97":"Program Control Nexus",
    "S98":"Collapsing Vent",
    "S99":"Prison Break",
    "S100":"Inside the Swarm",
    "S101":"Harrower Library",
    "S102":"Into the Black",
    "S103":"The Lead Door",
    "S104":"Ruins of the Solstice",
    "S105":"Ruins of the Equinox",
    "S106":"Tempus Forge",
    "S107":"My Private Empire",
    "S108":"Lustrous Pit",
    "S109":"Furious Factory",
    "S110":"Guardian's Temple",
    "S111":"Ice Cave",
    "S112":"Raised by Wolves",
    "S113":"Lush Grotto",
    "S114":"Work Freeze",
    "S115":"Pylon Problems",
    "S116":"Caravan Guards",
    "S117":"A Waiting Game",
    "S118":"Lurker Necromancy",
    "S119":"Radiant Dust",
    "S120":"Under the Influence",
    "S121":"Black Memories",
    "S122":"The Eternal Crave",
    "S123":"The Titan",
    "S124":"A Growing Problem",
    "S125":"The Longest Second",
    "S126":"Joseph the Lion",
    "S127":"Derelict Freighter",
    "S128":"A Tall Drunken Tale",
    "S129":"How to Lay an Ambush",
    "S130":"And Then, A Stream",
    "S131":"The Dancing Iceberg",
    "S132":"Temple of Feline Power",
    "S133":"Bolt",
    "S134":"Tower of Knowledge",
    "S135":"Belara's Keep",
    "S136":"Abandoned Hideout",
    "S137":"Pirate Queen's Haul",
    "So1":"Wonder of Nature",
    "So2":"Race Against the Clock",
    "So3":"Scouting Ambush",
    "So4":"The Dead of Night",
    "So5":"Bones in the Dirt",
    "So6":"Divide and Conquer",
    "So7":"Path of Ancestry",
    "So8":"Crumbling Descent",
    "So9":"Tuning the Resonance",
    "So10":"A Magnificent Trap",
    "So11":"A Collection of Suffering",
    "So12":"Fighting Snow with Snow",
    "So13":"Under the Ice",
    "So14":"Recharge",
    "So15":"Boiler Room",
    "So16":"Wet Work",
    "So17":"Crash Against the Waves",
  }
    app_tables.scenarios.add_row()
    for s_num, s_name in scenario_list.items():
      app_tables.scenarios.add_row(Number=s_num, Name=s_name)